---
kind: pipeline
type: docker
name: crypto-glue-amd64
platform:
  arch: amd64
  os: linux

steps:
  - name: build-crypto-glue-amd64
    image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
    pull: always
    environment:
      PATH: /bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:/root/.cargo/bin
      CODECOV_TOKEN:
        from_secret: codecov_token
    commands:
      - cargo build
      - cargo test
      - mkdir -p target/coverage
      - grcov . --binary-path ./target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o target/coverage/tests.lcov
      - codecov -B ${DRONE_BRANCH} -b ${DRONE_BUILD_NUMBER} -f target/coverage/tests.lcov -F amd64
trigger:
  event:
    - custom
    - push
---
kind: pipeline
type: docker
name: crypto-glue-arm64
platform:
  arch: arm64
  os: linux

steps:
  - name: build-crypto-glue-arm64
    image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
    pull: always
    environment:
      PATH: /bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:/root/.cargo/bin
      CODECOV_TOKEN:
        from_secret: codecov_token
    commands:
      - cargo build
      - cargo test
      - mkdir -p target/coverage
      - grcov . --binary-path ./target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o target/coverage/tests.lcov
      - codecov -B ${DRONE_BRANCH} -b ${DRONE_BUILD_NUMBER} -f target/coverage/tests.lcov -F arm64
trigger:
  event:
    - custom
    - push
